AWSTemplateFormatVersion: "2010-09-09"

Description: "Create IAM role"

Resources:
  Cloud9InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      RoleName: "amazonk8snetworkshop-admin"

  Cloud9InstancePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Cloud9InstancePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - !Ref Cloud9InstanceRole

  Cloud9InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Cloud9InstanceRole

Outputs:
  Cloud9WorkspaceRole:
    Description: "Role"
    Value: !Ref Cloud9InstanceRole
